### ISSUE TITLE
Notifications throw NPE when the document has been deleted

### ISSUE THREAD

**Issue by cmlewis** [tsgrp/HPI#250]
ActivitiNotificationImpl blindly grabs the first package item and tries to get its properties without doing a null check first.

Quick fix (that I should have put there anyway) is to add a null check. Long term though, we need some way to delete any outstanding notifications on a document when it is deleted.

Options:
- A scheduled job that goes through all notifications and deletes any with zero package items
- Alfresco behavior, but what about standalone Activiti?

@gsteimer or @dgrumieaux  any thoughts?

**Comment by gsteimer** [comment]
Marking this as an issue again.  When you alert someone a document, and then the document is deleted, a giant stack trace is presented to the user:

![image](https://cloud.githubusercontent.com/assets/1377228/7639813/5688496c-fa44-11e4-84e1-08b25e294de0.png)

I'm fine with swallowing the error for now.  The enhancement can be to clean up notifications for deleted objects.

**Comment by dgrumieaux** [comment]
Steps to reproduce:

- Start a simple workflow on document X
- Ensure user A is assigned to a task
- Delete document X
- With an Inbox configured on the dashboard, navigate to the dashboard as user A
- You will se the above stacktrace in a modal.

**Comment by gsteimer** [comment]
@dgrumieaux - as we discussed, this is actually a little simpler than what you have in your steps.  The steps to reproduce should be:

1. Notify User A of Document X using the Send Notification stage action
1. Delete Document X
1. Login as User A
  - Is an error presented to the user upon login?
  - When clicking on the view notifications bell, can I delete the notification?

**Comment by bridgetbol** [comment]
Fixed with OC commit: 12699
Fixed with HPI commit: 13179
CR - AVi 
added try catch to OC to eat error
added if else to HPI to determine id document was deleted

**Comment by gsteimer** [comment]
@bridgetbol - Talk to @aviking about some updates to your fix.

**Comment by bridgetbol** [comment]
OC - #12711 Reverted unnecessary OC commit #12699. Issue is still fixed with HPI commit #13179 
CR - Avi

**Comment by gsteimer** [comment]
I'm still seeing the same error on edge2.  Here's what I did:

1. Created an object
1. Notified it to myself
1. Verified notification
1. Logged out
1. Logged back in (see error below):

![image](https://cloud.githubusercontent.com/assets/1377228/10293846/71d8c2c4-6b7c-11e5-9d49-17825c5ed199.png)

@aviking @bridgetbol

**Comment by gsteimer** [comment]
On edge1, I get the following error every time the dashboard loads:

![image](https://cloud.githubusercontent.com/assets/1377228/10294250/a942e9e0-6b7e-11e5-9744-65fd4f3ff1c8.png)

**Comment by bridgetbol** [comment]
OC commit 12761 - Added OR statement to remove hpiWorkflowNotifications from get tasks. Added throw to ensure object will not pass through with null properties. CR - George

**Comment by gsteimer** [comment]
@bridgetbol @aviking - one small update I think is needed here - the con't actually doesn't know that the object is deleted, just that the user doesn't have access to it.  So, if I were to notify you of a document that you don't have permissions to read, you're going to see the message we have implemented here.  I think we just need to change the wording of the error message to something like:

`The document has either been deleted or you do not have access to it.`

**Comment by bridgetbol** [comment]
HPI commit 13304 - added "The document has either been deleted or you do not have access to it."
CR - Avi

**Comment by nquillin91** [comment]
Reopening - present in trunk again.

**Comment by dsubramanian92394** [comment]
OC commit 18071 - fixed Notification error when sending notification to document that user doesn't have READ access to.  Added code removed in an earlier OC revision.
