### ISSUE TITLE
Saved Search Dashlet doesn't show 10 per page initially.

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#525]
See the screencam below.  On edge 2, even though the saved search dashlet defaults to showing 10 per page, more than 10 are displayed on the first page.  It works if I change the per page dropdown and then change it back to 10.

Oddly, I can only reproduce this on edge2.  I don't think it's a repo specific thing.  Could it be a timing issue?

![no-results-ss](https://cloud.githubusercontent.com/assets/1377228/5669579/3481fa02-973e-11e4-80b4-3f1e18e5834c.gif)

**Comment by eric-gottschalk** [comment]
I think it is a timing issue. In savedsearchdashlet.js it is rendering the dashlet view twice. I think the view is being created which renders the view at line 181 and then the listener catches the trigger and renders the view again at line 207. The second re-render is there to pick up on when the next page or previous page buttons are clicked. Adding another check into the if statement on line 207, such as checking to see if the collection has changed, should fix the issue.

**Comment by eric-gottschalk** [comment]
Commit #11505
In savedsearchdashlet.js, changed if statement in the listener of the views.results view to render when the collection has a value and the query has returned. Moved the if statement before collection is initialized so it will not render on the dashlet initialize but will when a user navigates through the dashlet. 
CR: Zack Keller

**Comment by gsteimer** [comment]
Looks like this issue is back.  This time I can reproduce it on edge1 and edge2.  In both cases, if I change the per page dropdown to something else and then back to 10, it works fine:

**Edge1**
![image](https://cloud.githubusercontent.com/assets/1377228/20894976/30f0874a-badd-11e6-809f-52763286a327.png)


**Edge2**
![image](https://cloud.githubusercontent.com/assets/1377228/20894994/41a5b100-badd-11e6-9666-fa9109a74940.png)

**Comment by grahamsinger** [comment]
Fixed with rev16755.

**Comment by gsteimer** [comment]
@grahamsinger - see the screencam below.  It looks like the per-page issue is fixed when the dashboard is loaded, but now a new problem has arisen - you cannot click the next button until you change pages with the dropdown.

![saved-search-pagination-fail](https://cloud.githubusercontent.com/assets/1377228/20976509/4ed1125c-bc68-11e6-8fce-845aed1e382e.gif)

**Comment by grahamsinger** [comment]
Fixed with rev16763
